### ISSUE TITLE
Browser mistakenly opens new window in some conditions

### ISSUE THREAD

**Issue by Barmalej** [aquality-automation/aquality-selenium-java#67]
The issue can be reproduced when using combination of several conditions:
1) Using testng @BeforeMethod  annotation for setUp method, in witch Browser opens any website
2) Using timeout parameter in testng @Test annotation
3) Using method isDisplayed of any element of form from framework

e.g. as in  code below:

public class TestTimeout {

    @BeforeMethod
    public void setUp() {
        BrowserManager.getBrowser().goTo("https://ya.ru/");
    }

    @Test(timeOut = 1000000)
    public void testTimeout() {
        Assert.assertTrue(new ElementFactory().getLabel(By.id("text"), "name").state().isDisplayed());
    }
}

**Comment by knysh** [comment]
connected with https://github.com/cbeust/testng/issues/914
issue in testng, you can try to fix you issue by using ConditionalWait or run your test in one thread
